import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

// Dictionnaire des traductions

const translations = {
  //Francais
  FR: {
     "paidDays": "Jours payés",
  "unpaidDays": "Jours non payés",
  mixed:'mixte',
  holidaysThisMonth:'Jours fériés ce mois-ci',
  "holidaysIncluded": "Jours fériés inclus",
    "Parent Structure": "Structure parente",
  "Time Zone": "Fuseau horaire",
"company":'Entreprise',
'calendarVacationNoPaid':"Calendrier des congés non payés",
 "MonEntr": "Mon Entreprise",
  "structure": "Structure de l'entreprise",
  "graph": "Graphique de l'entreprise",
MonEntr_added: 'Mon entreprise a été ajoutée.',
addNewMonEntr: 'Ajouter une nouvelle entreprise',
telephone:'Téléphone',
site_web:'Site Web',
"salarydetails": "Détails du salaire",
  "employeename": "Nom de l'employé",
  "Mois": "Mois",
  "heuretravaillees": "Heures travaillées",
  "heures_supp": "Heures supplémentaires",
  "montant_heure_travail": "Montant heures normales",
  "montant_heures_supp": "Montant heures Sup",
  "montant_primes": "Montant des primes",
  "montant_remboursements": "Montant des remboursements",
  "montant_absences": "Montant des absences",
  "montant_conges": "Montant des congés",
  "anciennte": "Ancienneté",
  "monatn_prime_anciennete": "Prime d'ancienneté",
  "salaire_brut": "Salaire brut",
  "social_security": "Sécurité sociale (CNSS)",
  "health_insurance": "Assurance maladie (AMO)",
  "retirement_plan": "Retraite complémentaire (CIMR)",
  "ir": "Impôt sur le revenu (IR)",
  "salaire_net": "Salaire net",
  "close": "Fermer",
     "addNewCollectivePrime": "Ajouter une nouvelle prime collective",
      "employeePrimeDetails": "Détails de la prime de l’employé",
  "addNewEmployeePrime": "Ajouter une nouvelle prime pour l’employé",
  "employe_Prime_added": "Prime de l’employé ajoutée",
  "update_employee_prime": "Mettre à jour la prime de l’employé",
    currency:'Devise',
    processing:'Traitement...',
    "noEmployeeFound": "Aucun employé trouvé",
  "searchEmployee": "Rechercher un employé",
  "searchType": "Type de recherche",
  "noTypeFound": "Aucun type trouvé",
     "prime_employe": "Prime employé",
  "type_prime": "Type de prime",
  "primeDetails": "Détails de la prime",
  "update_prime": "Mettre à jour la prime",
  "addNewTypePrime": "Ajouter un nouveau type de prime",
  "TypePrimeadded": "Type de prime ajouté",
    addNewtauxheureSup :"Ajouter un nouveau taux d’heure supplémentaire",
    tauxheureSup_added :"Taux d’heure supplémentaire ajouté",
    update_tauxHeureSup:'Mettre à jour les détails des heures supplémentaires',
    tauxHeureSupDeatils:'Détails du taux des heures supplémentaires',
   trainingDetails :'Détails de la formation', 
   trainingEmployeeDetails :'Détails de la formation de l’employé',
    taux_heuresup:"Taux des heures supp",
    amountMonthly: "Montant Mensuel",
    'duration': 'Durée',
     "allStatus": "Tous les statuts",
    "dateValidation": "Date de validation",
     "justif": "Justificatif",
    "dateSoumission": "Date de soumission",
    date_maximum:'Date Maximum',
    "enterMontantmax": "Saisir le montant maximum",
     "montant_max": "Montant maximum",
  "remboRequests": "Demandes de remboursement",
  "typeRembo": "Type de remboursement",
  "allTypes": "Tous les types",
     "skillsAdded": "Compétences ajoutées",
    "copySkills": "Copier les compétences",
    "addNewSkills": "Ajouter de nouvelles compétences",
    "typeRemboDetails": "Détails du type de remboursement",
    // Sections
      "employeeRemboDetails": "Détails du remboursement de l’employé",
    "enterType": "Saisir le type",
    type:'Type',
    "update_typeRembo": "Mettre à jour le type de remboursement",
  "typeRembo_added": "Type de remboursement ajouté",
  "copy_typeRembo": "Copier le type de remboursement",
  "addNewtypeRembo": "Ajouter un nouveau type de remboursement",
      "jobTitles": "Intitulés de poste",
  "payGrades": "Échelles salariales",
  "employmentStatus": "Statut d’emploi",
    administration: "Administration",
    employeesSection: "Employés",
    "update_health_insurance.fr": "Mettre à jour l’assurance maladie",
"RetirementPlan_added": "Plan de retraite ajouté avec succès",
  "copy_RetirementPlan": "Copier le plan de retraite",
  "addNewRetirementPlan": "Ajouter un nouveau plan de retraite",
"year": "Année",
"health_insurance_Details": "Détails de l’assurance maladie",
  "social_security": "Sécurité sociale",
  social_security_Details:'Détails de la sécurité sociale',
"projectdetails": "Détails du projet",
 "projectname": "Nom du projet",
    nonWorkingDays: "Jours non travaillés",
nonWorkingDaysPlaceholder: "Weekends + Jours fériés",
adjustIfNeeded: "💡 Ajustez si nécessaire pour les jours fériés",
totalLeaveBalance: "Solde total",
remainingLeaveBalance: "Solde après congé",
insufficientBalance: "Solde insuffisant !",
periodInfoTitle: "Informations sur la période",
totalDuration: "Durée totale",
weekendsAndHolidays: "Weekends/Fériés",
days:'Jours',
effectiveLeaveDays: "Jours de congé effectifs",
 "overtimeRequests": "Demandes HS",
  "update_projects": "Mettre à jour les projets",
    // Main menu items
    dashboard: "Tableau de bord",
    admin: "Admin",
    employees: "Employés",
    manage: "Gérer",
    adminReports: "Rapports Admin",
    system: "Système",
    payroll: "Paie",
    personalInformation: "Informations Personnelles",
    training: "Formation",
    performanceManagement: "Gestion de la Performance",

    // Submenus (Admin)
    companyStructure: "Structure de l'entreprise",
    jobDetailsSetup: "Paramétrage des postes",
    qualificationsSetup: "Paramétrage des qualifications",
    resourcePerProject: "Ressources par projet",
    clients: "Clients",
    customFields: "Champs personnalisés",

    // Submenus (Manage)
    documents: "Documents",
    attendance: "Présences",
    overtime: "Heures supplémentaires",
    vacation: "Congés",
    loans: "Prêts",

    // Submenus (System)
    settings: "Paramètres",
    users: "Utilisateurs",
    managePermissions: "Gérer les permissions",

    // Submenus (Payroll)
    salary: "Salaire",

    // Submenus (Personal Info)
    personalDashboard: "Tableau de bord personnel",
    personalDocuments: "Documents personnels",
    personalVacation: "Congés personnels",

    // Submenus (Training)
    trainings: "Formations",

    // Submenus (Performance)
    goals: "Objectifs",
    annualReviews: "Entretiens annuels",
    feedback: "Retours",

    // Navigation
    home: 'Accueil',
    about: 'À propos',
    services: 'Services',
    contact: 'Contact',
    LeaveType:'Type de Congé',
    
    // Commun
    welcome: 'Bienvenue',
    login: 'Se connecter',
    logout: 'Se déconnecter',
    register: 'S\'inscrire',
    submit: 'Soumettre',
    cancel: 'Annuler',
    save: 'Enregistrer',
    delete: 'Supprimer',
    edit: 'Modifier',
    search: 'Rechercher',
    loading: 'Chargement...',
    employee:"Employé",
    
    // Messages
    success: 'Succès',
    error: 'Erreur',
    warning: 'Attention',
    info: 'Information',
    city:'Ville',
    // Formulaires
    name: 'Nom',
    email: 'Email',
    password: 'Mot de passe',
    confirmPassword: 'Confirmer le mot de passe',
    phone: 'Téléphone',
    address: 'Adresse',
    "addressInformation": "Informations d’adresse",
    // Dates
    today: 'Aujourd\'hui',
    yesterday: 'Hier',
    tomorrow: 'Demain',
     date: 'Date',
  timeIn: 'Heure d\'arrivée',
  timeOut: 'Heure de départ',
    // Actions
    viewMore: 'Voir plus',
    readMore: 'Lire la suite',
    download: 'Télécharger',
    upload: 'Téléverser',
    update: 'Modifier',
    addNew:'Ajouter ',
    export:'Exporter',
    close:'Fermer',
    search:'Rechercher...',
    allEmployees:'Tous les employés',
    loadingEmployees:'Chargement des employés',
    loadingData:'Chargement des données',

    // button
    cancel: "Annuler",
    add: "Ajouter",
    submit: "Soumettre",

    // exporter 
    "export_current_view": "Exporter la vue actuelle",
    "excel_current_view": "Excel (Vue actuelle)",
    "pdf_current_view": "PDF (Vue actuelle)",
    "export_all_data": "Exporter toutes les données",
    "excel_all_data": "Excel (Toutes les données)",
    "pdf_all_data": "PDF (Toutes les données)",

    //MODAL ADD NEW
    no_employee_found: "Aucun employé trouvé",
    search_employee: "Rechercher un employé...",
    enter_type:'Entrer le type de congé',
    enter_name: 'Entrez le nom de la formation',
    enter_reason:'Entrer la raison du congé',
    selectStatus:'Sélectionner le statut',
    selectTraining:'Sélectionner une formation',
    vacation_added: "Vacances ajoutées",
    training_added:"Formations ajoutées",
    copy_vacation: "Copier les vacances",
    addNewVacation: "Ajouter de nouvelles vacances",
    addNewTraining:"Ajouter de nouvelles formations",
    employee:"Employé",
    startDate:'Date Début',
    endDate:'Date fin',
    status:'Statut',
    reason:'Raison',
    supportingDocument:'Document justificatif',

    // MODAL VIEW
    vacationDetails:'Détails du congé',
    employeetrainingDetails:"Détails de la formation de l'employé",

    duraiton:'Durée',

    e_signature: 'E-Sign',
    edit_your_signature: 'Modifier votre signature',
    import_your_signature: 'Importer votre signature',
    upload_signature_image: 'Télécharger une image de signature',
    "rate": "Taux",
  "amount": "Montant",

    // edit modal
    update_vacation:'Modifier le congé',
    update_training:"Modifier la Formation",

    "autoCalculationTitle": "Calcul automatique du congé",
  "totalDuration": "Durée totale",
  "workingDays": "Jours ouvrables",
  "weekends": "Week-ends",
  "holidays": "Jours fériés",
  "nonWorkingDays": "Jours non travaillés (week-ends + fériés)",
  "daysToDeduct": "Jours à déduire du solde",
  "newBalance": "Nouveau solde après congé",
  "negativeBalanceWarning": "⚠️ Attention: Le solde sera négatif après ce congé",
  "days": "jours",

    no_employee_found: "Aucun employé trouvé",
    current_file: "Fichier actuel",
    replace_file_optional: "Remplacer le fichier (optionnel)",
    file: "Fichier",
    new_file_selected: "Nouveau fichier sélectionné :",
    saving: "Enregistrement...",
    save_changes: "Enregistrer les modifications",
     "update_success": "Les modifications ont été enregistrées avec succès !",
date:'Date',
    showing:'Affichage de',
    to:'à',
    of:'sur',
    results:'résultats',

    // DELETE MODAL 
    "deleted_success": "Supprimé avec succès",
    "item_removed": "L'élément a été supprimé définitivement.",
    "confirm_deletion": "Confirmer la suppression",
    "about_to_delete": "Vous êtes sur le point de supprimer :",
    "cannot_undo": "Cette action est irréversible !",
    "deleting": "Suppression en cours...",
    "delete_permanently": "Supprimer définitivement",

    job:"Poste",
note:'Note',
    //success
    successfully_added: "Ajouté avec succès !",
    training_successfully_added: "Formations ajoutées avec succès !",
    add_another: "Ajouter une autre",
    done: "Terminé",
    description: "Description",
    // Navigation de pages
    previous: 'Précédent',
    next: 'Suivant',
    page: 'Page',
    
    // Settings
    settings: 'Paramètres',
    profile: 'Profil',
    language: 'Langue',
    theme: 'Thème',
 "myproject": "Mes projets",
  "mesprojets": "Mes projets",
  "projectmanagement": "Gestion de projet",
    // Nouvelles traductions pour le tableau des vacances

    "All Months": "Tous les mois",
  "January": "Janvier",
  "February": "Février",
  "March": "Mars",
  "April": "Avril",
  "May": "Mai",
  "June": "Juin",
  "July": "Juillet",
  "August": "Août",
  "September": "Septembre",
  "October": "Octobre",
  "November": "Novembre",
  "December": "Décembre",
month:'Mois',
      "searchTrainingPlaceholder": "Rechercher une formation...",
  "searchEmployeePlaceholder": "Rechercher un employé...",
    calendarVacation: "Calendrier des Congés",
    employeeVacationRequests: "Demandes de Congé des Employés",
    leaveType: 'Type de Congé',
    startDate: 'Date de Début',
    endDate: 'Date de Fin',
    daysTaken: 'Jours Pris',
    "WorkSchedule_details": "Détails du planning de travail",

    leaveStatus: 'Statut du Congé',
    reason: 'Motif',
    file: 'Fichier',
    actions: 'Actions',
    noVacationFound:  "Aucune donnée trouvée",
    nofileattached:'Aucune Fichier Trouvé',
"overtime_details": "Détails des heures supplémentaires",
    soldeVacationTotal: 'Total congés',
soldeVacationRestant: 'Congés restants',
    january: 'Janvier',
    february: 'Février',
    march: 'Mars',
    april: 'Avril',
    may: 'Mai',
    june: 'Juin',
    july: 'Juillet',
    august: 'Août',
    september: 'Septembre',
    october: 'Octobre',
    november: 'Novembre',
    december: 'Décembre',
    "employee_projects": "Projets de l’employé",
    "educationAdded": "Éducation ajoutée", 
  "copyEducation": "Copier l’éducation", 
  "addNewEducation": "Ajouter une nouvelle éducation",
  "employee_projects_details": "Détails des projets de l’employé",
    // Jours de la semaine
    sun: 'Dim',
    mon: 'Lun',
    tue: 'Mar',
    wed: 'Mer',
    thu: 'Jeu',
    fri: 'Ven',
    sat: 'Sam',
    "addressInformation": "Informations d’adresse",
    "project": "Projet",
    "holidays": "Jours fériés",
    "nameHoliday": "Nom du jour férié",
     "project_added": "Projet ajouté",
  "copy_project": "Copier le projet",
  "add_new_project": "Ajouter un nouveau projet",
    // Navigation du calendrier
      "IR_added": "IR ajoutée avec succès",
  "copy_IR": "Copier IR",
  "addNewIR": "Ajouter une nouvelle IR",
    
    "workSchedule": "Planning de travail",
  "role": "Rôle",

   "languageAdded": "Langue ajoutée",
  "copyLanguage": "Copier la langue",
  "addNewLanguage": "Ajouter une nouvelle langue",
  "enterLanguage": "Saisir la langue",
  "updateLanguage": "Mettre à jour la langue",
  "languageDetails": "Détails de la langue",
  "language": "Langue",
    "fullName": "Nom complet",
  reimbursements: 'Notes des frais',
"update_overtime": "Mettre à jour les heures supplémentaires",
  "skillsDetails": "Détails des compétences",
  "educationDetails": "Détails de l’éducation",
    "employe_training_added": "Formation de l’employé ajoutée avec succès",
  "addNewEmployeFormation": "Ajouter une formation à un employé",
  "editEmployeFormation": "Modifier la formation de l’employé",
    // Statuts des congés
    approved: 'Approuvé',
    pending: 'En attente',
    rejected: 'Refusé',
    soldeVacation: 'Solde des congés',
    // Autres textes du calendrier
    unknown: 'Inconnu',
    leave: 'Congé',
    clickToViewDetails: 'Cliquez pour voir les détails de',
    employeesOnLeaveThisMonth: 'Employés en congé ce mois-ci',
 "update_social_security_rate": "Mettre à jour le taux de sécurité sociale",
    //TRAINING PAGE
     avaliableTrainings: "Formations Disponibles",
  trainingRequests: "Demandes de Formation",
  completedTrainings: "Formations Terminées",
"rate_and_tax": "Taux & Taxe",
   "rights_reserved": "Tous droits réservés par HR Linktis.",
"enterSkills": "Saisir des compétences",
"WorkSchedule_added": "Planning de travail ajouté",
  "copy_WorkSchedule": "Copier le planning de travail",
  "addNewWorkSchedule": "Ajouter un nouveau planning de travail",
  "update_WorkSchedule": "Mettre à jour le planning de travail",
   "allFormations": "Toutes les formations",
  "ongoing": "En cours",
  "completed": "Terminées",
   "notStarted": "Pas commencées",
health_insurance:'Assurance Maladie',
   "trainingname": "Nom de la formation",
  "employeename": "Nom de l’employé",
  skills:'Compétences',
workHours: "Heures de travail",
"update_Retirement_Plan": "Mettre à jour le plan de retraite",
all:'Toutes',
  "enterEducation": "Saisir l’éducation",
  "education": "Éducation",
   "updateEducation": "Mettre à jour l’éducation",
  "Overtime_added": "Heures supplémentaires ajoutées",
  "copy_overtime": "Copier les heures supplémentaires",
  "addNewOvertime": "Ajouter de nouvelles heures supplémentaires",
 updateCertifications:'Mettre à jour les certifications',
   certificationsDetails:'Détails des certifications',
timeInAfternoon: "Heure d'arrivée (Après-midi)",
timeOutAfternoon: "Heure de départ (Après-midi)",
    payroll: 'Paie',
  salary: 'Salaire',
  bonuses: 'Primes',
  certificationsDetails:'Détails des certifications',
  enterCertifications:'Saisir les certifications',
  deductions: 'Retenues',
  allowances: 'Allocations',
  payslips: 'Bulletins de paie',
  payrollSettings: 'Paramètres de paie',
employeeAttendanceDetails: "Détails de présence de l'employé",
 "employeeAttendance": "Présence des employés",
  "monthlyAttendance": "Présence mensuelle",
 "department": "Département",
  "jobTitle": "Intitulé du poste",
  "updateJob": "Mettre à jour le poste",
  "jobDetails": "Détails du poste",
  "jobAdded": "Poste ajouté",
  "copyJob": "Copier le poste",
  "addNewJob": "Ajouter un nouveau poste",
 "selectDepartment": "Sélectionnez un département",
  "jobName": "Nom du poste",
   "project_added": "Projet ajouté",
  "copy_project": "Copier le projet",
  "add_new_employee_project": "Ajouter un nouveau projet employé",
 "update_project_employee": "Mettre à jour le projet de l’employé",
"fullAddress": "Adresse complète",
"social_security_rate": "Taux de sécurité sociale",
 "AMO_added": "AMO ajoutée avec succès",
  "copy_AMO": "Copier l’AMO",
  "addNewAMO": "Ajouter une nouvelle AMO",
 "CNSS_added": "CNSS ajoutée",
  "copy_CNSS": "Copier une CNSS",
  "addNewCNSS": "Ajouter une nouvelle CNSS",
   legend:'Légende',
"update_health_insurance": "Mettre à jour l’assurance maladie",
  "country": "Pays",
  "retirement_plan": "Caisse de retraite",
   "RetirementPlanDetails": "Détails du plan de retraite",
    "from": "De ",
    "seniorityBonusDetails": "Détails de la prime d’ancienneté",
to:'à',
 "loadingCountries": "Chargement des pays...",
 "loadingDepartments": "Chargement des départements...",
  "selectCountry": "Sélectionnez un pays",
 "seniority_bonus": "Prime d’ancienneté",
  "seniority_bonus_added": "Prime d’ancienneté ajoutée avec succès",
  "copy_seniority_bonus": "Copier la prime d’ancienneté",
  "addNew_seniority_bonus": "Ajouter une nouvelle prime d’ancienneté",
  "update_seniority_bonus": "Mettre à jour la prime d’ancienneté",
   "anciennete_max": "Ancienneté maximale",
  "anciennete_min": "Ancienneté minimale",
  "clientAdded": "Client ajouté",
  "copyClient": "Copier le client",
  "addNewClient": "Ajouter un nouveau client",
  "updateClient": "Mettre à jour le client",
  "clientDetails": "Détails du client",
  "client": "Client",
  "enterClient": "Saisir le client",
"phoneNumber": "Numéro de téléphone",
ir:' Impôt sur le Revenu',
"health_insurance_rate": "Taux d’assurance maladie",
 "retirement_plan_rate": "Taux du plan de retraite",
   "InternalRevenueDetails": "Détails du Impôt sur le Revenu",
   "update_IR": "Mettre à jour IR",
     "certificationsAdded": "Certifications ajoutées",
  "copyCertifications": "Copier les certifications",
  "addNewCertifications": "Ajouter de nouvelles certifications",
certifications:"Certifications",
 "education": "Éducation",
  "certifications": "Certifications",
  "languages": "Langues",
  updateSkills:'Mettre à jour les compétences',
   "personalInformation": "Informations personnelles",


  },






  
  EN: {
     "addressInformation": "Address Information",
     "loadingCountries": "Loading countries...",
  "selectCountry": "Select a country",
  "personalInformation": "Personal Information",
    certifications:"Certifications",
    updateSkills:'Update Skills',
    ir:'Internal Revenue',
     "InternalRevenueDetails": "Internal revenue details",
    "seniority_bonus": "Seniority bonus",
  "update_health_insurance": "Update health insurance",
  "update_project_employee": "Update employee project",
  "employeeAttendance": "Employee Attendance",
  "monthlyAttendance": "Monthly Attendance",
nonWorkingDays: "Non-working days",
nonWorkingDaysPlaceholder: "Weekends + Public Holiday",
adjustIfNeeded: "💡 Adjust if needed for public holiday",
totalLeaveBalance: "Total leave balance",
remainingLeaveBalance: "Remaining leave balance",
insufficientBalance: "Insufficient balance!",
periodInfoTitle: "Period information",
totalDuration: "Total duration",
days:"Days",
weekendsAndHolidays: "Weekends/Public Holiday",
effectiveLeaveDays: "Effective leave days",
 "seniority_bonus_added": "Seniority bonus added successfully",
  "copy_seniority_bonus": "Copy seniority bonus",
  "addNew_seniority_bonus": "Add new seniority bonus",
  "educationAdded": "Education Added",
  "copyEducation": "Copy Education",
  "addNewEducation": "Add New Education",
timeOutAfternoon: "Time-Out (Afternoon)",
 date: 'Date',
  timeIn: 'Time-In',
  timeOut: 'Time-Out',
  note: 'Note',
  payroll: 'Payroll',
  salary: 'Salary',
  bonuses: 'Bonuses',
  deductions: 'Deductions',
  allowances: 'Allowances',
  payslips: 'Payslips',
  payrollSettings: 'Payroll settings',

   "jobTitles": "Job Titles",
  "payGrades": "Pay Grades",
  "employmentStatus": "Employment Status",
    // Sections
    administration: "Administration",
    employeesSection: "Employees",

    "autoCalculationTitle": "Automatic leave calculation",
  "totalDuration": "Total duration",
  "workingDays": "Working days",
  "weekends": "Weekends",
  "holidays": "Public holiday",
  "nonWorkingDays": "Non-working days (weekends + public holiday)",
  "daysToDeduct": "Days to deduct from balance",
  "newBalance": "New balance after leave",
  "negativeBalanceWarning": "⚠️ Warning: Balance will be negative after this leave",
  "days": "days",
health_insurance:'Health Insurance',
 "fullName": "Full name",
"update_health_insurance.en": "Update health insurance",
    // Main menu items
    dashboard: "Dashboard",
    admin: "Admin",
    employees: "Employees",
    manage: "Manage",
    adminReports: "Admin Reports",
    system: "System",
    payroll: "Payroll",
    personalInformation: "Personal Information",
    training: "Training",
    performanceManagement: "Performance Management",
    "projectdetails": "Project Details",

    "no_project_found": "Aucun projet trouvé",
    "no_employee_found": "Aucun employé trouvé",
    "role": "Role",
   // Submenus (Admin)
    companyStructure: "Company Structure",
    jobDetailsSetup: "Job Details Setup",
    qualificationsSetup: "Qualifications Setup",
    resourcePerProject: "Resources per Project",
    clients: "Clients",
    customFields: "Custom Fields",

    // Submenus (Manage)
    documents: "Documents",
    attendance: "Attendance",
    overtime: "Overtime",
    vacation: "Vacation",
    loans: "Loans",
 "employee_projects_details": "Employee Projects Details",
      "All Months": "All Months",
  "January": "January",
  "February": "February",
  "March": "March",
  "April": "April",
  "May": "May",
  "June": "June",
  "July": "July",
  "August": "August",
  "September": "September",
  "October": "October",
  "November": "November",
  "December": "December",
"WorkSchedule_details": "Work Schedule Details",
   "skillsAdded": "Skills Added",
    "copySkills": "Copy Skills",
    "addNewSkills": "Add New Skills",
    // Submenus (System)
    settings: "Settings",
    users: "Users",
    managePermissions: "Manage Permissions",

    // Submenus (Payroll)
    salary: "Salary",

    "update_projects": "Update Projects",

    // Submenus (Personal Info)
    personalDashboard: "Personal Dashboard",
    personalDocuments: "Personal Documents",
    personalVacation: "Personal Vacation",
"overtime_details": "Overtime Details",
    // Submenus (Training)
    trainings: "Trainings",
    "project_added": "Project added",
  "copy_project": "Copy project",
  "add_new_project": "Add new project",
 "update_seniority_bonus": "Update seniority bonus",
    // Submenus (Performance)
    goals: "Goals",
    annualReviews: "Annual Reviews",
    feedback: "Feedback",
"nameHoliday": "Public Holiday name",
    // Navigation
    home: 'Home',
    about: 'About',
    services: 'Services',
      "IR_added": "IR added successfully",
  "copy_IR": "Copy IR",
  "addNewIR": "Add new IR",
    contact: 'Contact',
    skills:'Skills',
    city:'City',
     "myproject": "My Projects",
  "mesprojets": "My Projects",
  "projectmanagement": "Project Management",
  "social_security_Details": "Social security details",
 "seniorityBonusDetails": "Seniority bonus details",
    "showing": "Showing",
  "to": "to",
  "of": "of",
  "results": "results",
    "rate": "Rate",
  "amount": "Amount",
  "loadingDepartments": "Loading departments...",
    // Common
    welcome: 'Welcome',
    login: 'Login',
    logout: 'Logout',
    register: 'Register',
    submit: 'Submit',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    search: 'Search...',
    loading: 'Loading...',
    
    // Messages
    success: 'Success',
    error: 'Error',
    warning: 'Warning',
    info: 'Information',

    "RetirementPlan_added": "Retirement plan added successfully",
  "copy_RetirementPlan": "Copy retirement plan",
  "addNewRetirementPlan": "Add new retirement plan",
    certificationsDetails:'Certifications Details',
  enterCertifications:'Enter Certifications',
    // Forms
    name: 'Name',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    leaveType:'Leave Type',
    phone: 'Phone',
    address: 'Address',
    
    // Dates
    today: 'Today',
    yesterday: 'Yesterday',
    tomorrow: 'Tomorrow',
"update_WorkSchedule": "Update Work Schedule",
    //Button
    cancel: "Cancel",
    add: "Add",
    submit: "Submit",
 reimbursements: 'Expense Reports',
    // Actions
    viewMore: 'View More',
    readMore: 'Read More',
    download: 'Download',
    upload: 'Upload',
    update: 'Update',
    copy:'Copy',
    addNew:'Add New',
    export:'Export',
    search:'Search',
    close:'Close',
    allEmployees:'All Employees',
    loadingEmployees:'Loading Employees',
    loadingData:'Loading Data',
    "workSchedule": "Work Schedule",
    "clientAdded": "Client Added",
  "copyClient": "Copy Client",
  "addNewClient": "Add New Client",
  "updateClient": "Update Client",
  "clientDetails": "Client Details",
  "client": "Client",
  "enterClient": "Enter Client",
 "role": "Role",
 "social_security": "Social Security",
"update_social_security_rate": "Update social security rate",
"languageAdded": "Language Added",
  "copyLanguage": "Copy Language",
  "addNewLanguage": "Add New Language",
  "enterLanguage": "Enter Language",
  "updateLanguage": "Update Language",
  "languageDetails": "Language Details",
  "language": "Language",

  "health_insurance_Details": "Health insurance details",
    //exporter
    "export_current_view": "Export Current View",
    "excel_current_view": "Excel (Current View)",
    "pdf_current_view": "PDF (Current View)",
    "export_all_data": "Export All Data",
    "excel_all_data": "Excel (All Data)",
    "pdf_all_data": "PDF (All Data)",
     "certificationsAdded": "Certifications Added",
  "copyCertifications": "Copy Certifications",
  "addNewCertifications": "Add New Certifications",
"skillsDetails": "Skills Details",
  "educationDetails": "Education Details",
    // Edit Vacation
    update_vacation:'Update Vacation',
update_training:'Update Training',
    no_employee_found: "No employee found",
    current_file: "Current file",
    replace_file_optional: "Replace file (optional)",
    file: "file",
    new_file_selected: "New file selected :",
    saving: "Saving...",
    save_changes: "Saving changes",
    "update_success": "Changes have been successfully saved !",
   "overtimeRequests": "Overtime Requests",
    // DELETE MODAL
    deleted_success: "Successfully Deleted",
    item_removed: "The item has been permanently removed.",
    confirm_deletion: "Confirm Deletion",
    about_to_delete: "You are about to delete:",
    cannot_undo: "This action cannot be undone!",
    deleting: "Deleting...",
     "country": "Country",
    delete_permanently: "Delete Permanently",
    "projectname": "Project name",
    "update_Retirement_Plan": "Update retirement plan",
  "year": "Year",
    successfully_added: "Successfully added !",
   training_successfully_added: "Training successfully added!",
    add_another: "Add Another",
    done: "Done",
soldeVacation: 'Leave balance',
  "no_project_found": "No project found",
  "no_employee_found": "No employee found",
"update_overtime": "Update Overtime",
    enter_reason:'Enter Reason for leave',
    enter_name:'Enter training name',
    enter_type:'Enter leave type',
    selectStatus:'Select Status',
    selectTraining:'Select a training',
    no_employee_found: "No employee found",
    search_employee: "Search for an employee...",
    vacation_added: "Vacation Added ",
    training_added: "Training Added ",
    copy_vacation: "Copy Vacation",
    addNewVacation: "Add New Vacation",
    addNewTraining: "Add New Training",
    employee:"Employee",
    startDate:'Start Date',
    endDate:'End Date',
    status:'Status',
    reason:'Reason',
"project_added": "Project Added",
  "copy_project": "Copy Project",
  "add_new_employee_project": "Add New Employee Project",
  "update_IR": "Update IR",
   "education": "Education",
  "certifications": "Certifications",
  "languages": "Languages",
    supportingDocument:'Supporting Document',
soldeVacationTotal: 'Total leave',
soldeVacationRestant: 'Remaining leave',
    vacationDetails:'Vacation Details',
    employeetrainingDetails:'Employee training details',
    duraiton:'Days Taken',
     "rate_and_tax": "Rate & Tax",
     "health_insurance_rate": "Health insurance rate",
    previous: 'Previous',
    next: 'Next',
    page: 'Page',
     "project": "Project",
    settings: 'Settings',
    profile: 'Profile',
    language: 'Language',
    theme: 'Theme',
 "enterEducation": "Enter Education",
  "education": "Education",
  "updateEducation": "Update Education",
    job:"Job",
"phoneNumber": "Phone number",
    e_signature: 'E-Sign',
    edit_your_signature: 'Edit your signature',
    import_your_signature: 'Import your signature',
    upload_signature_image: 'Upload a signature image',

      "social_security_rate": "Social Security Rate",
  "Overtime_added": "Overtime Added",
  "copy_overtime": "Copy Overtime",
  "addNewOvertime": "Add New Overtime",
"employee_projects": "Employee Projects",

    // Vacation table translations
    calendarVacation:"Calendar Vacation",
    employeeVacationRequests:"Employee Vacation Requests",
 "searchTrainingPlaceholder": "Search for a training...",
  "searchEmployeePlaceholder": "Search for an employee...",
    startDate: 'Start Date',
    endDate: 'End Date',
    daysTaken: 'Days Taken',
    leaveStatus: 'Leave Status',
    reason: 'Reason',
    file: 'File',
    actions: 'Actions',
    noVacationFound: 'No Data found',
    nofileattached:'No File Attached',
workHours: "Work Hours",

 "CNSS_added": "CNSS added",
  "copy_CNSS": "Copy CNSS",
  "addNewCNSS": "Add new CNSS",
    january: 'January',
    february: 'February',
    march: 'March',
    april: 'April',
    may: 'May',
    june: 'June',
    july: 'July',
    august: 'August',
    september: 'September',
    october: 'October',
    november: 'November',
    december: 'December',
    timeInAfternoon: "Time-In (Afternoon)",
    timeOutAfternoon: "Time-Out (Afternoon)",
all:'All',
    employeeAttendanceDetails: "Employee Attendance Details",
  "WorkSchedule_added": "Work Schedule Added",
  "copy_WorkSchedule": "Copy Work Schedule",
  "addNewWorkSchedule": "Add New Work Schedule",
  "enterSkills": "Enter skills",
   "addressInformation": "Address Information",
     "fullAddress": "Full address",
    // Jours de la semaine
    sun: 'Sun',
    mon: 'Mon',
    tue: 'Tue',
    wed: 'Wed',
    thu: 'Thu',
    fri: 'Fri',
    sat: 'Sat',
    
    // Navigation du calendrier
   updateCertifications:'Update Certifications',
   certificationsDetails:'Certifications Details',
  
    
    // Statuts des congés
    approved: 'Approved',
    pending: 'Pending',
    rejected: 'Rejected',
    
    // Autres textes du calendrier
    unknown: 'Unknown',
    leave: 'Leave',
    clickToViewDetails: 'Click to view details for',
    employeesOnLeaveThisMonth: 'Employees on leave this month',
description: "Description",
month:'Month',
 "allFormations": "All trainings",
  "ongoing": "Ongoing",
  "completed": "Completed",
  "notStarted": "Not started",
   "from": "From ",
to:'To',

  "anciennete_max": "Maximum seniority",
  "anciennete_min": "Minimum seniority",

   "employe_training_added": "Employee training successfully added",
  "addNewEmployeFormation": "Add new employee training",
  "editEmployeFormation": "Edit employee training",
    // TRAINING PAGE
     avaliableTrainings: "Available Trainings",
  trainingRequests: "Training Requests", 
  completedTrainings: "Completed Trainings",
"trainingname": "Training Name",
  "employeename": "Employee Name",

  "rights_reserved": "All rights reserved by HR Linktis.",
   "holidays": "Public holiday",
   date:'Date',
   legend:'Legend',
    "AMO_added": "AMO added successfully",
     "department": "Department",
  "jobTitle": "Job Title",
  "updateJob": "Update Job",
  "jobDetails": "Job Details",
  "jobAdded": "Job Added",
  "copyJob": "Copy Job",
  "addNewJob": "Add New Job",
  "copy_AMO": "Copy AMO",
  "addNewAMO": "Add new AMO",
  "retirement_plan": "Retirement Plan",
  "RetirementPlanDetails": "Retirement plan details",
  "selectDepartment": "Select Department",
  "jobName": "Job Name",
   "saving": "Saving..."
  },

  // Espagne
  ES: {
    "loadingDepartments": "Cargando departamentos...",
      "selectDepartment": "Seleccione un departamento",
  "jobName": "Nombre del puesto",
    "addressInformation": "Información de dirección",
    all:'Todos',
     "department": "Departamento",
  "jobTitle": "Título del puesto",
  "updateJob": "Actualizar puesto",
  "jobDetails": "Detalles del puesto",
  "jobAdded": "Puesto añadido",
  "copyJob": "Copiar puesto",
  "addNewJob": "Agregar nuevo puesto",

     "rate": "Tasa",
  "amount": "Importe",
  certificationsDetails:'Detalles de certificaciones',
  enterCertifications:'Ingresar certificaciones',
  "languageAdded": "Idioma añadido",
  "copyLanguage": "Copiar idioma",
  "addNewLanguage": "Agregar nuevo idioma",
  "enterLanguage": "Ingresar idioma",
  "updateLanguage": "Actualizar idioma",
  "languageDetails": "Detalles del idioma",
  "language": "Idioma",
  "from": "De ",
   "skillsDetails": "Detalles de habilidades",
  "educationDetails": "Detalles de la educación",
to:'A',
"clientAdded": "Cliente añadido",
  "copyClient": "Copiar cliente",
  "addNewClient": "Agregar nuevo cliente",
  "updateClient": "Actualizar cliente",
  "clientDetails": "Detalles del cliente",
  "client": "Cliente",
  "enterClient": "Ingresar cliente",

skills:'Habilidades',
  "education": "Educación",
  "certifications": "Certificaciones",
  "languages": "Idiomas",
    "RetirementPlanDetails": "Detalles del plan de jubilación",
  "RetirementPlan_added": "Plan de jubilación agregado con éxito",
  "copy_RetirementPlan": "Copiar plan de jubilación",
  "addNewRetirementPlan": "Agregar nuevo plan de jubilación",
    legend:'Leyenda',
    "holidays": "Días festivos",
 "update_seniority_bonus": "Actualizar la prima de antigüedad",
nonWorkingDays: "Días no laborables",
days:'Días',
nonWorkingDaysPlaceholder: "Fines de semana + Festivos",
adjustIfNeeded: "💡 Ajuste si es necesario por festivos",
totalLeaveBalance: "Saldo total de vacaciones",
remainingLeaveBalance: "Saldo restante de vacaciones",
insufficientBalance: "¡Saldo insuficiente!",
periodInfoTitle: "Información del período",
totalDuration: "Duración total",
weekendsAndHolidays: "Fines de semana/Festivos",
effectiveLeaveDays: "Días efectivos de vacaciones",
"WorkSchedule_details": "Detalles del horario de trabajo",
"workSchedule": "Horario de trabajo",
 payroll: 'Nómina',
  salary: 'Salario',
  bonuses: 'Bonificaciones',
    "country": "País",
  deductions: 'Deducciones',
  allowances: 'Asignaciones',
  payslips: 'Recibos de sueldo',
  payrollSettings: 'Configuración de nómina',
"update_overtime": "Actualizar horas extra",
  "overtimeRequests": "Solicitudes de horas extra",
  "project_added": "Proyecto añadido",
  "copy_project": "Copiar proyecto",
  "add_new_project": "Agregar nuevo proyecto",
   "rate_and_tax": "Tasa & Impuesto",
   "seniority_bonus": "Prima de antigüedad",
    "seniority_bonus_added": "Prima de antigüedad agregada con éxito",
  "copy_seniority_bonus": "Copiar la prima de antigüedad",
  "addNew_seniority_bonus": "Agregar nueva prima de antigüedad",
    "educationAdded": "Educación añadida",
  "copyEducation": "Copiar educación",
  "addNewEducation": "Agregar nueva educación",
  "seniorityBonusDetails": "Detalles de la prima de antigüedad",
   "enterEducation": "Ingresar educación",
  "education": "Educación",
  "updateEducation": "Actualizar educación",
    "certificationsAdded": "Certificaciones añadidas",
  "copyCertifications": "Copiar certificaciones",
  "addNewCertifications": "Agregar nuevas certificaciones",

   "jobTitles": "Títulos de trabajo",
  "payGrades": "Escalas salariales",
  "employmentStatus": "Estado de empleo",
    // Sections
    city:'Ciudad',
    "loadingCountries": "Cargando países...",
  "selectCountry": "Seleccione un país",
    administration: "Administración",
    employeesSection: "Empleados",
    "overtime_details": "Detalles de las horas extra",
    "role": "Rol",
    dashboard: "Panel de Control",
    admin: "Admin",
    employees: "Empleados",
    manage: "Gestionar",
    adminReports: "Informes Admin",
    system: "Sistema",
    payroll: "Nómina",
    personalInformation: "Información Personal",
    training: "Formación",
    performanceManagement: "Gestión del Rendimiento",
    "update_WorkSchedule": "Actualizar horario de trabajo",
    "update_IR": "Actualizar IR",
"project": "Proyecto",
"no_project_found": "No se encontró proyecto",
  "no_employee_found": "No se encontró empleado",
  "projectname": "Nombre del proyecto",
    // Submenus (Admin)
    companyStructure: "Estructura de la Empresa",
    jobDetailsSetup: "Configuración de Puestos",
    qualificationsSetup: "Configuración de Cualificaciones",
    resourcePerProject: "Recursos por Proyecto",
    clients: "Clientes",
    customFields: "Campos Personalizados",

     "IR_added": "IR agregada con éxito",
  "copy_IR": "Copiar IR",
  "addNewIR": "Agregar nueva IR",
soldeVacation: 'Saldo de vacaciones',

"update_projects": "Actualizar proyectos",
ir:'Agencia Tributaria',
soldeVacationTotal: 'Total vacaciones',
soldeVacationRestant: 'Vacaciones restantes',
workHours: "Horas de trabajo",
"WorkSchedule_added": "Horario de trabajo añadido",
"copy_WorkSchedule": "Copiar horario de trabajo",
"addNewWorkSchedule": "Agregar nuevo horario de trabajo",
"projectdetails": "Detalles del proyecto",
"social_security_Details": "Detalles de la seguridad social",
  "fullName": "Nombre completo",
    documents: "Documentos",
    attendance: "Asistencia",
    overtime: "Horas Extra",
    vacation: "Vacaciones",
    loans: "Préstamos",
reimbursements: 'Informes de gastos',
  "fullAddress": "Dirección completa",
    // Submenus (System)
    "phoneNumber": "Número de teléfono",
     "addressInformation": "Información de dirección",
    settings: "Configuración",
    users: "Usuarios",
    managePermissions: "Gestionar Permisos",
"personalInformation": "Información personal",
     "project_added": "Proyecto añadido",
  "copy_project": "Copiar proyecto",
  "add_new_employee_project": "Agregar nuevo proyecto de empleado",
   "InternalRevenueDetails": "Detalles de ingresos internos",
updateSkills:'Actualizar habilidades',
"Overtime_added": "Horas extra añadidas",
  "copy_overtime": "Copiar horas extra",
  "addNewOvertime": "Agregar nuevas horas extra",
   month:'Mes',
   timeIn: 'Hora de entrada',
   timeOut: 'Hora de salida',
   note: 'Nota',
  "social_security_rate": "Tasa de seguridad social",
   "skillsAdded": "Habilidades añadidas",
    "copySkills": "Copiar habilidades",
    "addNewSkills": "Agregar nuevas habilidades",
    // Submenus (Payroll)
  salary: "Salario",
  "social_security": "Seguridad Social",
"update_social_security_rate": "Actualizar la tasa de seguridad social",
  "showing": "Mostrando",
  "to": "a",
  "of": "de",
  "results": "resultados",
   "CNSS_added": "CNSS añadida",
  "copy_CNSS": "Copiar CNSS",
  "addNewCNSS": "Agregar nueva CNSS",
  "health_insurance_rate": "Tasa de seguro de salud",
  "year": "Año",
   "anciennete_max": "Antigüedad máxima",
  "anciennete_min": "Antigüedad mínima" ,
  "enterSkills": "Ingresar habilidades",
    // Submenus (Personal Info)
    personalDashboard: "Panel Personal",
    personalDocuments: "Documentos Personales",
    personalVacation: "Vacaciones Personales",
    employeeAttendanceDetails: "Detalles de asistencia del empleado",
    health_insurance:'Seguro de Salud',
"update_health_insurance": "Actualizar el seguro de salud" ,
  "employeeAttendance": "Asistencia de empleados",
  "health_insurance_Details": "Detalles del seguro de salud",
  "monthlyAttendance": "Asistencia mensual",
    // Submenus (Training)
    trainings: "Entrenamientos",
   "update_project_employee": "Actualizar proyecto del empleado",
    // Submenus (Performance)
    goals: "Objetivos",
    annualReviews: "Evaluaciones Anuales",
    feedback: "Retroalimentación",
   "employee_projects_details": "Detalles de los proyectos del empleado",
     "employee_projects": "Proyectos del empleado",
    // Navigation
    home: 'Inicio',
    about: 'Acerca de',
    services: 'Servicios',
    contact: 'Contacto',
    LeaveType: 'Tipo de Permiso',
    "retirement_plan": "Plan de jubilación",
    
    "autoCalculationTitle": "Cálculo automático de la licencia",
  "totalDuration": "Duración total",
  "workingDays": "Días laborables",
  "weekends": "Fines de semana",
  "holidays": "Días festivos",
  "nonWorkingDays": "Días no laborables (fines de semana + festivos)",
  "daysToDeduct": "Días a deducir del saldo",
  "newBalance": "Nuevo saldo después de la licencia",
  "negativeBalanceWarning": "⚠️ Atención: El saldo será negativo después de esta licencia",
  "days": "días",
timeInAfternoon: "Hora de entrada (Tarde)",
timeOutAfternoon: "Hora de salida (Tarde)",

  "All Months": "Todos los meses",
  "January": "Enero",
  "February": "Febrero",
  "March": "Marzo",
  "April": "Abril",
  "May": "Mayo",
  "June": "Junio",
  "July": "Julio",
  "August": "Agosto",
  "September": "Septiembre",
  "October": "Octubre",
  "November": "Noviembre",
  "December": "Diciembre",
    // Common
    certifications:"Certificaciones",
    welcome: 'Bienvenido',
    login: 'Iniciar Sesión',
    logout: 'Cerrar Sesión',
    updateCertifications:"Actualizar certificaciones",
    certificationsDetails:'Detalles de certificaciones',
    register: 'Registrarse',
    submit: 'Enviar',
    cancel: 'Cancelar',
    save: 'Guardar',
    delete: 'Eliminar',
    edit: 'Editar',
    search: 'Buscar...',
    loading: 'Cargando...',
    employee: "Empleado",
    "update_health_insurance.es": "Actualizar el seguro de salud",

  "AMO_added": "AMO agregada con éxito",
  "copy_AMO": "Copiar AMO",
  "addNewAMO": "Agregar nueva AMO",
    "myproject": "Mis proyectos",
  "mesprojets": "Mis proyectos",
  "projectmanagement": "Gestión de proyectos",
    
    // Messages
    success: 'Éxito',
    error: 'Error',
    warning: 'Advertencia',
    info: 'Información',
    
    // Formulaires
    name: 'Nombre',
    email: 'Correo',
    password: 'Contraseña',
    confirmPassword: 'Confirmar Contraseña',
    phone: 'Teléfono',
    address: 'Dirección',
    
    // Dates
    today: 'Hoy',
    yesterday: 'Ayer',
    tomorrow: 'Mañana',
     "nameHoliday": "Nombre del día festivo",
    // Actions
    viewMore: 'Ver Más',
    readMore: 'Leer Más',
    download: 'Descargar',
    upload: 'Subir',
    update: 'Actualizar',
    addNew: 'Agregar Nuevo',
    export: 'Exportar',
    close: 'Cerrar',
    search: 'Buscar...',
    allEmployees: 'Todos los Empleados',
    loadingEmployees: 'Cargando Empleados',
    loadingData: 'Cargando Datos',
    description: "Descripción",
    // button
    cancel: "Cancelar",
    add: "Agregar",
    submit: "Enviar",

    // exporter 
    "export_current_view": "Exportar Vista Actual",
    "excel_current_view": "Excel (Vista Actual)",
    "pdf_current_view": "PDF (Vista Actual)",
    "export_all_data": "Exportar Todos los Datos",
    "excel_all_data": "Excel (Todos los Datos)",
    "pdf_all_data": "PDF (Todos los Datos)",

    //MODAL ADD NEW
    no_employee_found: "Ningún empleado encontrado",
    search_employee: "Buscar un empleado...",
    enter_type: 'Ingrese el tipo de permiso',
    enter_name: 'Ingrese el nombre de la formación',
    enter_reason: 'Ingrese la razón del permiso',
    selectStatus: 'Seleccionar Estado',
    selectTraining:'Seleccionar Formación',
    vacation_added: "Vacaciones Agregadas",
    training_added: "Formación Agregadas",
    copy_vacation: "Copiar Vacaciones",
    addNewVacation: "Agregar Nuevas Vacaciones",
    addNewTraining: "Agregar Nuevas Formación",
    employee: "Empleado",
    startDate: 'Fecha de Inicio',
    endDate: 'Fecha de Fin',
    status: 'Estado',
    reason: 'Razón',
    date:'Fecha',
    supportingDocument: 'Documento de Apoyo',

    // MODAL VIEW
    vacationDetails: 'Detalles de Vacaciones',
    employeetrainingDetails: 'Detalles de la formación del empleado',
    duraiton: 'Duración',

    e_signature: 'F.Élec',
    edit_your_signature: 'Editar tu firma',
    import_your_signature: 'Importar tu firma',
    upload_signature_image: 'Subir imagen de firma',

    update_vacation: 'Actualizar Vacaciones',
    update_training:'Actualizar Formación',

    no_employee_found: "Ningún empleado encontrado",
    current_file: "Archivo actual",
    replace_file_optional: "Reemplazar archivo (opcional)",
    file: "Archivo",
    new_file_selected: "Nuevo archivo seleccionado:",
    saving: "Guardando...",
    save_changes: "Guardar Cambios",
     "update_success": "Los cambios se han guardado con éxito !",

    // DELETE MODAL 
    "deleted_success": "Eliminado con Éxito",
    "item_removed": "El elemento ha sido eliminado permanentemente.",
    "confirm_deletion": "Confirmar Eliminación",
    "about_to_delete": "Estás a punto de eliminar:",
    "cannot_undo": "¡Esta acción no se puede deshacer!",
    "deleting": "Eliminando...",
    "delete_permanently": "Eliminar Permanentemente",

    job: "Puesto",

    "searchTrainingPlaceholder": "Buscar una formación...",
  "searchEmployeePlaceholder": "Buscar un empleado...",
"employe_training_added": "Formación del empleado añadida con éxito",
  "addNewEmployeFormation": "Agregar formación a un empleado",
  "editEmployeFormation": "Editar la formación del empleado",
    //success
    successfully_added: "Añadido con éxito!",
    training_successfully_added: "Formación del empleado agregadas con éxito!",
    add_another: "Agregar Otra",
    done: "Terminado",
    
    // Navigation de pages
    previous: 'Anterior',
    next: 'Siguiente',
    page: 'Página',
    
    // Settings
    settings: 'Configuración',
    profile: 'Perfil',
    language: 'Idioma',
    theme: 'Tema',

    // Nouvelles traductions pour le tableau des vacances
    calendarVacation: "Calendario de Vacaciones",
    employeeVacationRequests: "Solicitudes de Vacaciones de Empleados",
    leaveType: 'Tipo de Permiso',
    startDate: 'Fecha de Inicio',
    endDate: 'Fecha de Fin',
    daysTaken: 'Días Tomados',
    leaveStatus: 'Estado del Permiso',
    reason: 'Motivo',
    file: 'Archivo',
    actions: 'Acciones',
    noVacationFound: 'No se encontraron datos',
    nofileattached: 'Ningún Archivo Adjunto',

    january: 'Enero',
    february: 'Febrero',
    march: 'Marzo',
    april: 'Abril',
    may: 'Mayo',
    june: 'Junio',
    july: 'Julio',
    august: 'Agosto',
    september: 'Septiembre',
    october: 'Octubre',
    november: 'Noviembre',
    december: 'Diciembre',
    
    // Jours de la semaine
    sun: 'Dom',
    mon: 'Lun',
    tue: 'Mar',
    wed: 'Mié',
    thu: 'Jue',
    fri: 'Vie',
    sat: 'Sáb',
    
    
    approved: 'Aprobado',
    pending: 'Pendiente',
    rejected: 'Rechazado',
    
    // Autres textes du calendrier
    unknown: 'Desconocido',
    leave: 'Permiso',
    clickToViewDetails: 'Haga clic para ver los detalles de',
    employeesOnLeaveThisMonth: 'Empleados de permiso este mes',
  "allFormations": "Todas las formaciones",
  "ongoing": "En curso",
  "completed": "Completadas",
"notStarted": "No iniciadas",

    // TRAINING 
    avaliableTrainings: "Formaciones Disponibles",
trainingRequests: "Solicitudes de Formación",
completedTrainings: "Formaciones Completadas",

"rights_reserved": "Todos los derechos reservados por HR Linktis.",
 "trainingname": "Nombre de la formación",
  "employeename": "Nombre del empleado",
"update_Retirement_Plan": "Actualizar el plan de jubilación",
  },



  
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState('FR');

  // Charger la langue depuis localStorage au démarrage
  useEffect(() => {
    const savedLanguage = localStorage.getItem('selectedLanguage');
    if (savedLanguage && translations[savedLanguage]) {
      setCurrentLanguage(savedLanguage);
    }
  }, []);

  // Sauvegarder la langue dans localStorage
  const changeLanguage = (languageCode) => {
    setCurrentLanguage(languageCode);
    localStorage.setItem('selectedLanguage', languageCode);
    
    // Optionnel: changer la direction du document pour l'arabe
    if (languageCode === 'AR') {
      document.documentElement.dir = 'rtl';
      document.documentElement.lang = 'ar';
    } else {
      document.documentElement.dir = 'ltr';
      document.documentElement.lang = languageCode.toLowerCase();
    }
  };

  // Fonction pour obtenir une traduction
  const t = (key) => {
    return translations[currentLanguage]?.[key] || key;
  };

  // Fonction pour obtenir la direction du texte
  const getTextDirection = () => {
    return currentLanguage === 'AR' ? 'rtl' : 'ltr';
  };

  const value = {
    currentLanguage,
    changeLanguage,
    t,
    getTextDirection,
    isRTL: currentLanguage === 'AR'
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

// Hook personnalisé pour utiliser le contexte
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};